apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-vqvu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/dc-metro-map-vqvu@sha256:15792ee9a4c395f3e9134df65d5a49d0be501b182129dac619820adc0c1dfd0f
        name: my-nodejs
        resources: {}
status: {}
